//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuideHoundEPG.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuideHoundEPG.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tv
        ///  generator-info-name=&quot;EPGCollector/2.0.16.0&quot;&gt;
        ///  &lt;channel
        ///    id=&quot;1302&quot;&gt;
        ///    &lt;display-name&gt;TV3 PLUS1&lt;/display-name&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel
        ///    id=&quot;1300&quot;&gt;
        ///    &lt;display-name&gt;TV3&lt;/display-name&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel
        ///    id=&quot;1301&quot;&gt;
        ///    &lt;display-name&gt;C4&lt;/display-name&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel
        ///    id=&quot;1303&quot;&gt;
        ///    &lt;display-name&gt;C42&lt;/display-name&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel
        ///    id=&quot;1200&quot;&gt;
        ///    &lt;display-name&gt;TV ONE&lt;/display-name&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bsepg_epid {
            get {
                return ResourceManager.GetString("bsepg_epid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tv date=&quot;20100427011502 +1200&quot; generator-info-name=&quot;epgsnoop-grabber&quot;&gt;
        ///		&lt;programme channel=&quot;tv1.freeviewnz.tv&quot; start=&quot;20100426004500 +1200&quot; stop=&quot;20100426011000 +1200&quot;&gt;
        ///		&lt;title&gt;Auction House&lt;/title&gt;
        ///		&lt;desc&gt;A local series that goes behind-the-scenes in the world of auctions, art and antiques.&lt;/desc&gt;
        ///		&lt;subtitles type=&quot;teletext&quot; /&gt;
        ///		&lt;rating system=&quot;Freeview&quot;&gt;
        ///			&lt;value&gt;G&lt;/value&gt;
        ///		&lt;/rating&gt;
        ///	&lt;/programme&gt;
        ///	&lt;programme channel=&quot;tv1.freeviewnz.tv&quot; start=&quot;20100426060000 +1200&quot; stop=&quot;20100426063000 +1200&quot;&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string datetime {
            get {
                return ResourceManager.GetString("datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tv date=&quot;20100427011502 +1200&quot; generator-info-name=&quot;epgsnoop-grabber&quot;&gt;
        ///	&lt;channel id=&quot;tv1.freeviewnz.tv&quot;&gt;
        ///		&lt;display-name&gt;TV One&lt;/display-name&gt;
        ///		&lt;icon src=&quot;http://www.freeviewnz.tv/images/uploads/tv_one.jpg&quot; /&gt;
        ///	&lt;/channel&gt;
        ///	&lt;channel id=&quot;tv2.freeviewnz.tv&quot;&gt;
        ///		&lt;display-name&gt;TV2&lt;/display-name&gt;
        ///		&lt;icon src=&quot;http://www.freeviewnz.tv/images/uploads/tv_2.jpg&quot; /&gt;
        ///	&lt;/channel&gt;
        ///	&lt;channel id=&quot;tv3.freeviewnz.tv&quot;&gt;
        ///		&lt;display-name&gt;TV3&lt;/display-name&gt;
        ///		&lt;icon src=&quot;http://www.freeviewnz.tv/images/uploads/tv_3.jpg&quot; /&gt;
        ///	&lt;/cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string freeview {
            get {
                return ResourceManager.GetString("freeview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tv date=&quot;20100510125202 +1200&quot; generator-info-name=&quot;epgsnoop-grabber&quot;&gt;
        ///  &lt;channel id=&quot;tv1.freeviewnz.tv&quot;&gt;
        ///    &lt;display-name&gt;TV One&lt;/display-name&gt;
        ///    &lt;icon src=&quot;http://www.freeviewnz.tv/images/uploads/tv_one.jpg&quot; /&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel id=&quot;tv2.freeviewnz.tv&quot;&gt;
        ///    &lt;display-name&gt;TV2&lt;/display-name&gt;
        ///    &lt;icon src=&quot;http://www.freeviewnz.tv/images/uploads/tv_2.jpg&quot; /&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel id=&quot;tv3.freeviewnz.tv&quot;&gt;
        ///    &lt;display-name&gt;TV3&lt;/display-name&gt;
        ///    &lt;icon src=&quot;http://www.freeviewnz.tv/images/uploads/tv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string freeview2 {
            get {
                return ResourceManager.GetString("freeview2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE tv SYSTEM &quot;xmltv.dtd&quot;&gt;
        ///&lt;tv generator-info-name=&quot;unit test&quot;&gt;
        ///  &lt;channel id=&quot;01&quot;&gt;
        ///    &lt;display-name&gt;TV1&lt;/display-name&gt;
        ///    &lt;icon src=&quot;http://www.gbpvr.com/logo/TV1.jpeg&quot; /&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel id=&quot;02&quot;&gt;
        ///    &lt;display-name&gt;TV2&lt;/display-name&gt;
        ///    &lt;display-name&gt;TV2-ALTERNATIVE&lt;/display-name&gt;
        ///    &lt;icon src=&quot;icons\colour\2.png&quot; /&gt;
        ///  &lt;/channel&gt;
        ///  &lt;channel id=&quot;03&quot;&gt;
        ///    &lt;display-name&gt;TV3&lt;/display-name&gt;
        ///    &lt;icon src=&quot;icons\colour\3.png&quot; /&gt;
        ///  &lt;/channel&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testfile1 {
            get {
                return ResourceManager.GetString("testfile1", resourceCulture);
            }
        }
    }
}
